services:
  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: <YourStrong@Passw0rd>
    ports:
      - 1433:1433
  smtp:
    image: rnwood/smtp4dev:v3
    ports:
      - 3001:80
      - 25:25
    environment:
      - ServerOptions__HostName=smtp4dev
  node:
    image: debian:12-slim
    ports:
      - 3000:3000
    stdin_open: true # used to keep container running
    tty: true
    user: "${UID_GID}"
    environment:
      HOME: "${USER_HOME}"
    volumes:
    - ./:/HIERR
    - ${USER_HOME}:${USER_HOME}
