import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { NextPageButtonLink } from "../UI/NextPageButtonLink";

import React from "react";

import WhatIsHierr from "../components/WhatIsHierr";
import AboutThisEngagementPortal from "../components/AboutThisEngagement";
import WhyCreateAccount from "../components/WhyCreateAccount";

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Welcome to HIERR</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
          integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
        />
        <link
          rel="stylesheet"
          href="https://unpkg.com/esri-leaflet-geocoder/dist/esri-leaflet-geocoder.css"
        />
        <script
          src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
          integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
          async
        />
      </Head>
      <main
        className="relative flex  h-screen flex-col items-center justify-center  
      overflow-hidden bg-spectrum bg-blend-screen "
      >
        <div
          className="3xl:top-96 fixed  top-28 
        flex flex-col items-center justify-center  md:top-48 2xl:top-60"
        >
          <h1
            className="mx-2 pb-5 text-center text-4xl 
            font-extrabold leading-none tracking-tight text-white
           md:text-6xl"
          >
            Welcome to the HIERR Project
          </h1>
          <h2
            className="mx-2 pb-20 text-center text-2xl font-bold leading-none 
            tracking-tight
             text-white
             md:text-5xl lg:pb-16"
          >
            Engagement Portal
          </h2>
          <AuthShowcase />
          <WhatIsHierr />
          <AboutThisEngagementPortal />
          <WhyCreateAccount />
        </div>
      </main>
    </>
  );
};

export default Login;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData ? (
          <NextPageButtonLink pageName="censusmap" msg="Click here to begin." />
        ) : null}
      </p>
      <button
        className="text-black rounded-full bg-white/80 px-6 py-2 text-lg  
        no-underline transition ease-in-out hover:bg-white"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in to begin"}
      </button>
    </div>
  );
};
